services:
  app:
    container_name: app_prefeitura_front
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        VITE_APP_NODE_ENV: ${VITE_APP_NODE_ENV}
    environment:
      - VITE_APP_NODE_ENV=${VITE_APP_NODE_ENV}
    ports:
      - "83:80"
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
