services:
  app:
    container_name: app_prefeitura_front
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "83:80"
    environment:
      NODE_ENV: development
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
