server {
    # Or other port
    listen 80 default_server;
    # IPV6 is disabled
    
    server_name app_prefeitura;
    location /api {
        proxy_pass http://192.168.16.200:3001/api;
        proxy_http_version 1.1;
        x-real-ip $remote_addr;
    }

    location /ft/ {
        proxy_pass http://192.168.16.200:3002/ft/;
        proxy_http_version 1.1;
        x-real-ip $remote_addr;
    }

    # Servir aplicação React
    root /usr/share/nginx/app_prefeitura;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}