server {
    # Or other port
    listen 80 default_server;
    # IPV6 is disabled
    
    server_name app_prefeitura;
    location /api {
        proxy_pass http://app_prefeitura_gateway:3000/api/v2;
        proxy_http_version 1.1;
    }

    location /ft {
        proxy_pass http://app_prefeitura_frente_trabalho:3000/ft;
        proxy_http_version 1.1;
    }

    # Servir aplicação React
    root /usr/share/nginx/app_prefeitura;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
